name: Instant Merge PRs

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - assigned
    paths:
      - README.md

permissions:
  packages: write
  contents: read
  id-token: write

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - id: instant-merge
        run: |
          echo ${{ github.event }}
